version: '3'
services: 
    redis-server:
        image: 'redis'
        restart: always
    py-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: [ "8000:8000" ]
        volumes: 
            - .:/opt
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: "no"
        volumes: 
            - .:/opt
        command: [ pytest, test ]
                    