version: '3'
services: 
    redis-server:
        image: 'redis'
        restart: always
    app: &app
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on:
          - redis-server
        ports: [ "8000:8000" ]
        volumes: 
            - .:/opt
    run: 
        <<: *app
    test:
        <<: *app
        restart: "no"
        command: [ pytest, test ]
                    